### ISSUE TITLE
Release the "dist" folder

### ISSUE THREAD

**Issue by hmil** [senhungwong/http-exceptions#2]
Hi, the module on npm does not contain the "dist" folder (which contains the compiled TypeScript). Make sure to run `npm run build` before you release the module 😉

**Comment by 5u4** [comment]
Ops, first time publish node module, didn't know that. I guess it is fixed now on v1.1.1.

**Comment by hmil** [comment]
👍 Yes it is working.

I'm building the middleware in [this repo](https://github.com/hmil/express-youch) if you want to check it out.
